import { Node, Edge } from 'reactflow';
import { ServiceNodeData } from '@/lib/stores/designer-store';
import { getServiceById } from '@/lib/aws-services';

export interface TerraformFile {
  path: string;
  content: string;
}

export interface TerraformProject {
  files: TerraformFile[];
}

// Generate modular Terraform project
export function generateTerraformProject(
  nodes: Node<ServiceNodeData>[],
  edges: Edge[]
): TerraformProject {
  const files: TerraformFile[] = [];

  if (nodes.length === 0) {
    files.push({
      path: 'main.tf',
      content: `# No resources to generate
# Drag AWS services onto the canvas to create your architecture`,
    });
    return { files };
  }

  // Generate main.tf with provider
  files.push({
    path: 'main.tf',
    content: generateMainTf(nodes),
  });

  // Generate variables.tf
  files.push({
    path: 'variables.tf',
    content: generateVariablesTf(nodes),
  });

  // Generate outputs.tf
  files.push({
    path: 'outputs.tf',
    content: generateOutputsTf(nodes),
  });

  // Generate module files for each service type
  const serviceTypes = new Set(nodes.map((n) => n.data.serviceId));

  serviceTypes.forEach((serviceId) => {
    const serviceNodes = nodes.filter((n) => n.data.serviceId === serviceId);
    const moduleFiles = generateServiceModule(serviceId, serviceNodes, edges, nodes);
    files.push(...moduleFiles);
  });

  // Generate README
  files.push({
    path: 'README.md',
    content: generateReadme(nodes),
  });

  return { files };
}

// Legacy single-file export for preview
export function generateTerraform(
  nodes: Node<ServiceNodeData>[],
  edges: Edge[]
): string {
  const project = generateTerraformProject(nodes, edges);
  return project.files.map((f) => `# === ${f.path} ===\n${f.content}`).join('\n\n');
}

function sanitizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '_');
}

function generateMainTf(nodes: Node<ServiceNodeData>[]): string {
  const serviceTypes = new Set(nodes.map((n) => n.data.serviceId));

  let content = `# Generated by Archyra Architecture Designer
# Main Terraform Configuration

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # Uncomment to use remote state
  # backend "s3" {
  #   bucket = "your-terraform-state-bucket"
  #   key    = "state/terraform.tfstate"
  #   region = "us-east-1"
  # }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Environment = var.environment
      ManagedBy   = "Terraform"
      Project     = var.project_name
    }
  }
}

# Module Instances
`;

  // Add module calls
  serviceTypes.forEach((serviceId) => {
    const serviceNodes = nodes.filter((n) => n.data.serviceId === serviceId);
    serviceNodes.forEach((node) => {
      const resourceName = sanitizeName(node.data.serviceName);
      content += `
module "${resourceName}" {
  source = "./modules/${serviceId}"

  name        = "${resourceName}"
  environment = var.environment
  ${generateModuleInputs(node)}
}
`;
    });
  });

  return content;
}

function generateModuleInputs(node: Node<ServiceNodeData>): string {
  const props = node.data.properties;
  const lines: string[] = [];

  Object.entries(props).forEach(([key, value]) => {
    if (value !== '' && value !== undefined && value !== null) {
      if (typeof value === 'string') {
        lines.push(`  ${key} = "${value}"`);
      } else if (typeof value === 'boolean') {
        lines.push(`  ${key} = ${value}`);
      } else if (typeof value === 'number') {
        lines.push(`  ${key} = ${value}`);
      }
    }
  });

  return lines.join('\n');
}

function generateVariablesTf(nodes: Node<ServiceNodeData>[]): string {
  return `# Generated by Archyra Architecture Designer
# Input Variables

variable "aws_region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name (e.g., dev, staging, prod)"
  type        = string
  default     = "production"
}

variable "project_name" {
  description = "Project name for tagging"
  type        = string
  default     = "archyra-project"
}
`;
}

function generateOutputsTf(nodes: Node<ServiceNodeData>[]): string {
  let content = `# Generated by Archyra Architecture Designer
# Outputs

`;

  nodes.forEach((node) => {
    const resourceName = sanitizeName(node.data.serviceName);
    const serviceId = node.data.serviceId;

    content += `output "${resourceName}_id" {
  description = "ID of ${node.data.serviceName}"
  value       = module.${resourceName}.id
}

`;
  });

  return content;
}

function generateServiceModule(
  serviceId: string,
  nodes: Node<ServiceNodeData>[],
  edges: Edge[],
  allNodes: Node<ServiceNodeData>[]
): TerraformFile[] {
  const files: TerraformFile[] = [];

  // Module main.tf
  files.push({
    path: `modules/${serviceId}/main.tf`,
    content: generateModuleMain(serviceId, nodes, allNodes),
  });

  // Module variables.tf
  files.push({
    path: `modules/${serviceId}/variables.tf`,
    content: generateModuleVariables(serviceId),
  });

  // Module outputs.tf
  files.push({
    path: `modules/${serviceId}/outputs.tf`,
    content: generateModuleOutputs(serviceId),
  });

  return files;
}

function generateModuleMain(
  serviceId: string,
  nodes: Node<ServiceNodeData>[],
  allNodes: Node<ServiceNodeData>[]
): string {
  switch (serviceId) {
    case 'ec2':
      return generateEC2Module();
    case 'lambda':
      return generateLambdaModule();
    case 's3':
      return generateS3Module();
    case 'rds':
      return generateRDSModule();
    case 'dynamodb':
      return generateDynamoDBModule();
    case 'api-gateway':
      return generateAPIGatewayModule();
    case 'cloudfront':
      return generateCloudFrontModule();
    case 'sqs':
      return generateSQSModule();
    case 'sns':
      return generateSNSModule();
    case 'cognito':
      return generateCognitoModule();
    case 'vpc':
      return generateVPCModule();
    case 'ecs':
      return generateECSModule();
    case 'elasticache':
      return generateElastiCacheModule();
    case 'iam':
      return generateIAMModule();
    case 'route53':
      return generateRoute53Module();
    case 'vpc-environment':
      return generateVpcEnvironmentModule();
    case 'public-subnet':
      return generatePublicSubnetModule();
    case 'private-subnet':
      return generatePrivateSubnetModule();
    case 'alb':
      return generateALBModule();
    case 'nlb':
      return generateNLBModule();
    case 'nat-gateway':
      return generateNatGatewayModule();
    default:
      return `# TODO: Add ${serviceId} module configuration\n`;
  }
}

function generateEC2Module(): string {
  return `# EC2 Instance Module

data "aws_ami" "selected" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = [var.ami == "amazon-linux-2023" ? "al2023-ami-*-x86_64" :
              var.ami == "amazon-linux-2" ? "amzn2-ami-hvm-*-x86_64-gp2" :
              var.ami == "ubuntu-24" ? "ubuntu/images/hvm-ssd/ubuntu-noble-24.04-amd64-server-*" :
              var.ami == "ubuntu-22" ? "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" :
              "amzn2-ami-hvm-*-x86_64-gp2"]
  }
}

resource "aws_instance" "this" {
  ami           = data.aws_ami.selected.id
  instance_type = var.instanceType

  root_block_device {
    volume_size = var.rootVolumeSize
    volume_type = var.rootVolumeType
    encrypted   = true
  }

  associate_public_ip_address = var.publicIp
  key_name                    = var.keyPair != "" ? var.keyPair : null
  monitoring                  = var.monitoring

  tags = {
    Name = var.instanceName
  }
}
`;
}

function generateLambdaModule(): string {
  return `# Lambda Function Module

resource "aws_iam_role" "lambda" {
  name = "\${var.name}_role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "lambda.amazonaws.com"
      }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "lambda_basic" {
  role       = aws_iam_role.lambda.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

resource "aws_lambda_function" "this" {
  filename         = "\${path.module}/lambda_placeholder.zip"
  function_name    = var.functionName
  role             = aws_iam_role.lambda.arn
  handler          = var.handler
  runtime          = var.runtime
  memory_size      = var.memory
  timeout          = var.timeout
  architectures    = [var.architecture]

  reserved_concurrent_executions = var.reservedConcurrency >= 0 ? var.reservedConcurrency : null

  dynamic "environment" {
    for_each = length(var.envVars) > 0 ? [1] : []
    content {
      variables = { for line in split("\\n", var.envVars) :
        split("=", line)[0] => split("=", line)[1] if length(split("=", line)) == 2
      }
    }
  }

  tracing_config {
    mode = var.enableTracing ? "Active" : "PassThrough"
  }

  tags = {
    Name = var.name
  }
}
`;
}

function generateS3Module(): string {
  return `# S3 Bucket Module

resource "aws_s3_bucket" "this" {
  bucket = var.bucketName

  tags = {
    Name = var.name
  }
}

resource "aws_s3_bucket_versioning" "this" {
  bucket = aws_s3_bucket.this.id

  versioning_configuration {
    status = var.versioning ? "Enabled" : "Suspended"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "this" {
  count  = var.encryption != "none" ? 1 : 0
  bucket = aws_s3_bucket.this.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = var.encryption == "aws:kms" ? "aws:kms" : "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "this" {
  bucket = aws_s3_bucket.this.id

  block_public_acls       = var.publicAccess
  block_public_policy     = var.publicAccess
  ignore_public_acls      = var.publicAccess
  restrict_public_buckets = var.publicAccess
}

resource "aws_s3_bucket_website_configuration" "this" {
  count  = var.staticHosting ? 1 : 0
  bucket = aws_s3_bucket.this.id

  index_document {
    suffix = var.indexDocument
  }

  error_document {
    key = var.errorDocument
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "this" {
  count  = var.lifecycleEnabled ? 1 : 0
  bucket = aws_s3_bucket.this.id

  rule {
    id     = "lifecycle-rule"
    status = "Enabled"

    transition {
      days          = var.transitionDays
      storage_class = "STANDARD_IA"
    }

    dynamic "expiration" {
      for_each = var.expirationDays > 0 ? [1] : []
      content {
        days = var.expirationDays
      }
    }
  }
}

resource "aws_s3_bucket_cors_configuration" "this" {
  count  = var.enableCors ? 1 : 0
  bucket = aws_s3_bucket.this.id

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["GET", "HEAD", "PUT", "POST", "DELETE"]
    allowed_origins = ["*"]
    max_age_seconds = 3000
  }
}
`;
}

function generateRDSModule(): string {
  return `# RDS Database Module

resource "aws_db_instance" "this" {
  identifier     = var.identifier
  engine         = var.engine
  engine_version = var.engine == "postgres" ? "16" : var.engine == "mysql" ? "8.0" : null

  instance_class        = var.instanceClass
  allocated_storage     = var.allocatedStorage
  max_allocated_storage = var.maxAllocatedStorage
  storage_type          = var.storageType
  storage_encrypted     = true

  db_name  = var.dbName
  username = var.masterUsername
  password = var.password
  port     = var.port

  multi_az               = var.multiAz
  publicly_accessible    = var.publiclyAccessible
  backup_retention_period = var.backupRetention
  deletion_protection    = var.deletionProtection
  skip_final_snapshot    = !var.deletionProtection

  performance_insights_enabled = var.performanceInsights

  tags = {
    Name = var.name
  }
}
`;
}

function generateDynamoDBModule(): string {
  return `# DynamoDB Table Module

resource "aws_dynamodb_table" "this" {
  name         = var.tableName
  billing_mode = var.billingMode
  hash_key     = var.hashKey

  dynamic "range_key" {
    for_each = var.rangeKey != "" ? [1] : []
    content {
      # This is handled in the attribute block
    }
  }

  attribute {
    name = var.hashKey
    type = var.hashKeyType
  }

  dynamic "attribute" {
    for_each = var.rangeKey != "" ? [1] : []
    content {
      name = var.rangeKey
      type = var.rangeKeyType
    }
  }

  dynamic "ttl" {
    for_each = var.ttlAttribute != "" ? [1] : []
    content {
      attribute_name = var.ttlAttribute
      enabled        = true
    }
  }

  point_in_time_recovery {
    enabled = var.pointInTimeRecovery
  }

  dynamic "stream_specification" {
    for_each = var.enableStreams ? [1] : []
    content {
      stream_enabled   = true
      stream_view_type = var.streamViewType
    }
  }

  tags = {
    Name = var.name
  }
}
`;
}

function generateAPIGatewayModule(): string {
  return `# API Gateway Module

resource "aws_apigatewayv2_api" "this" {
  name          = var.apiName
  protocol_type = var.apiType

  dynamic "cors_configuration" {
    for_each = var.corsEnabled ? [1] : []
    content {
      allow_origins = split(",", var.corsOrigins)
      allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers = ["*"]
    }
  }

  tags = {
    Name = var.name
  }
}

resource "aws_apigatewayv2_stage" "this" {
  api_id      = aws_apigatewayv2_api.this.id
  name        = var.stageName
  auto_deploy = true

  default_route_settings {
    throttling_burst_limit = var.throttlingBurstLimit
    throttling_rate_limit  = var.throttlingRateLimit
  }

  dynamic "access_log_settings" {
    for_each = var.enableAccessLogs ? [1] : []
    content {
      destination_arn = aws_cloudwatch_log_group.api_logs[0].arn
      format          = jsonencode({
        requestId      = "$context.requestId"
        ip             = "$context.identity.sourceIp"
        requestTime    = "$context.requestTime"
        httpMethod     = "$context.httpMethod"
        routeKey       = "$context.routeKey"
        status         = "$context.status"
        responseLength = "$context.responseLength"
      })
    }
  }
}

resource "aws_cloudwatch_log_group" "api_logs" {
  count = var.enableAccessLogs ? 1 : 0
  name  = "/aws/apigateway/\${var.name}"
}
`;
}

function generateCloudFrontModule(): string {
  return `# CloudFront Distribution Module

resource "aws_cloudfront_distribution" "this" {
  enabled             = true
  comment             = var.comment
  default_root_object = var.defaultRootObject
  price_class         = var.priceClass

  origin {
    domain_name = var.origin_domain_name
    origin_id   = "primary"

    custom_origin_config {
      http_port              = 80
      https_port             = 443
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["TLSv1.2"]
    }
  }

  default_cache_behavior {
    allowed_methods        = ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "primary"
    viewer_protocol_policy = var.viewerProtocol
    compress               = var.enableCompression

    min_ttl     = var.minTtl
    default_ttl = var.defaultTtl
    max_ttl     = var.maxTtl

    forwarded_values {
      query_string = true
      cookies {
        forward = "none"
      }
    }
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }

  tags = {
    Name = var.name
  }
}
`;
}

function generateSQSModule(): string {
  return `# SQS Queue Module

resource "aws_sqs_queue" "this" {
  name                       = var.fifoQueue ? "\${var.queueName}.fifo" : var.queueName
  fifo_queue                 = var.fifoQueue
  content_based_deduplication = var.fifoQueue ? var.contentBasedDedup : null

  visibility_timeout_seconds = var.visibilityTimeout
  message_retention_seconds  = var.messageRetention
  max_message_size           = var.maxMessageSize
  delay_seconds              = var.delaySeconds
  receive_wait_time_seconds  = var.receiveWaitTime

  sqs_managed_sse_enabled = var.enableEncryption

  tags = {
    Name = var.name
  }
}

resource "aws_sqs_queue" "dlq" {
  count = var.enableDlq ? 1 : 0
  name  = var.fifoQueue ? "\${var.queueName}-dlq.fifo" : "\${var.queueName}-dlq"
  fifo_queue = var.fifoQueue

  tags = {
    Name = "\${var.name}-dlq"
  }
}

resource "aws_sqs_queue_redrive_policy" "this" {
  count     = var.enableDlq ? 1 : 0
  queue_url = aws_sqs_queue.this.id

  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.dlq[0].arn
    maxReceiveCount     = var.maxReceiveCount
  })
}
`;
}

function generateSNSModule(): string {
  return `# SNS Topic Module

resource "aws_sns_topic" "this" {
  name                        = var.fifoTopic ? "\${var.topicName}.fifo" : var.topicName
  display_name                = var.displayName
  fifo_topic                  = var.fifoTopic
  content_based_deduplication = var.fifoTopic ? var.contentBasedDedup : null

  kms_master_key_id = var.kmsMasterKeyId != "" ? var.kmsMasterKeyId : null

  tags = {
    Name = var.name
  }
}
`;
}

function generateCognitoModule(): string {
  return `# Cognito User Pool Module

resource "aws_cognito_user_pool" "this" {
  name                     = var.poolName
  mfa_configuration        = var.mfaConfiguration
  username_attributes      = [var.usernameAttributes]
  auto_verified_attributes = [var.autoVerifiedAttributes]

  password_policy {
    minimum_length    = var.passwordMinLength
    require_uppercase = var.passwordRequireUppercase
    require_lowercase = var.passwordRequireLowercase
    require_numbers   = var.passwordRequireNumbers
    require_symbols   = var.passwordRequireSymbols
  }

  admin_create_user_config {
    allow_admin_create_user_only = var.allowAdminUserCreation
  }

  verification_message_template {
    default_email_option = "CONFIRM_WITH_CODE"
    email_message        = var.emailVerificationMessage
  }

  tags = {
    Name = var.name
  }
}

resource "aws_cognito_user_pool_client" "this" {
  name         = "\${var.name}_client"
  user_pool_id = aws_cognito_user_pool.this.id

  generate_secret = false

  explicit_auth_flows = [
    "ALLOW_USER_PASSWORD_AUTH",
    "ALLOW_REFRESH_TOKEN_AUTH",
    "ALLOW_USER_SRP_AUTH"
  ]
}
`;
}

function generateVPCModule(): string {
  return `# VPC Module

resource "aws_vpc" "this" {
  cidr_block           = var.cidrBlock
  enable_dns_hostnames = var.enableDnsHostnames
  enable_dns_support   = var.enableDnsSupport

  tags = {
    Name = var.vpcName
  }
}

resource "aws_internet_gateway" "this" {
  vpc_id = aws_vpc.this.id

  tags = {
    Name = "\${var.name}-igw"
  }
}

resource "aws_subnet" "public" {
  count                   = var.publicSubnets
  vpc_id                  = aws_vpc.this.id
  cidr_block              = cidrsubnet(var.cidrBlock, 8, count.index)
  availability_zone       = data.aws_availability_zones.available.names[count.index % length(data.aws_availability_zones.available.names)]
  map_public_ip_on_launch = true

  tags = {
    Name = "\${var.name}-public-\${count.index + 1}"
    Type = "public"
  }
}

resource "aws_subnet" "private" {
  count             = var.privateSubnets
  vpc_id            = aws_vpc.this.id
  cidr_block        = cidrsubnet(var.cidrBlock, 8, count.index + var.publicSubnets)
  availability_zone = data.aws_availability_zones.available.names[count.index % length(data.aws_availability_zones.available.names)]

  tags = {
    Name = "\${var.name}-private-\${count.index + 1}"
    Type = "private"
  }
}

resource "aws_eip" "nat" {
  count  = var.enableNatGateway ? (var.singleNatGateway ? 1 : var.publicSubnets) : 0
  domain = "vpc"

  tags = {
    Name = "\${var.name}-nat-eip-\${count.index + 1}"
  }
}

resource "aws_nat_gateway" "this" {
  count         = var.enableNatGateway ? (var.singleNatGateway ? 1 : var.publicSubnets) : 0
  allocation_id = aws_eip.nat[count.index].id
  subnet_id     = aws_subnet.public[count.index].id

  tags = {
    Name = "\${var.name}-nat-\${count.index + 1}"
  }
}

data "aws_availability_zones" "available" {
  state = "available"
}
`;
}

function generateECSModule(): string {
  return `# ECS Module

resource "aws_ecs_cluster" "this" {
  name = var.clusterName

  setting {
    name  = "containerInsights"
    value = "enabled"
  }

  tags = {
    Name = var.name
  }
}

resource "aws_ecs_task_definition" "this" {
  family                   = var.serviceName
  network_mode             = "awsvpc"
  requires_compatibilities = [var.launchType == "FARGATE_SPOT" ? "FARGATE" : var.launchType]
  cpu                      = var.cpu
  memory                   = var.memory
  execution_role_arn       = aws_iam_role.ecs_execution.arn

  container_definitions = jsonencode([{
    name      = var.serviceName
    image     = "nginx:latest"
    essential = true
    portMappings = [{
      containerPort = var.containerPort
      hostPort      = var.containerPort
      protocol      = "tcp"
    }]
    healthCheck = {
      command     = ["CMD-SHELL", "curl -f http://localhost\${var.healthCheckPath} || exit 1"]
      interval    = 30
      timeout     = 5
      retries     = 3
      startPeriod = 60
    }
    logConfiguration = {
      logDriver = "awslogs"
      options = {
        "awslogs-group"         = aws_cloudwatch_log_group.ecs.name
        "awslogs-region"        = data.aws_region.current.name
        "awslogs-stream-prefix" = "ecs"
      }
    }
  }])

  tags = {
    Name = var.name
  }
}

resource "aws_ecs_service" "this" {
  name            = var.serviceName
  cluster         = aws_ecs_cluster.this.id
  task_definition = aws_ecs_task_definition.this.arn
  desired_count   = var.desiredCount
  launch_type     = var.launchType == "FARGATE_SPOT" ? "FARGATE" : var.launchType

  dynamic "capacity_provider_strategy" {
    for_each = var.launchType == "FARGATE_SPOT" ? [1] : []
    content {
      capacity_provider = "FARGATE_SPOT"
      weight            = 1
    }
  }

  network_configuration {
    subnets          = var.subnet_ids
    security_groups  = [aws_security_group.ecs.id]
    assign_public_ip = true
  }

  tags = {
    Name = var.name
  }
}

resource "aws_appautoscaling_target" "this" {
  count              = var.enableAutoScaling ? 1 : 0
  max_capacity       = var.maxCapacity
  min_capacity       = var.minCapacity
  resource_id        = "service/\${aws_ecs_cluster.this.name}/\${aws_ecs_service.this.name}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"
}

resource "aws_iam_role" "ecs_execution" {
  name = "\${var.name}-ecs-execution"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "ecs-tasks.amazonaws.com"
      }
    }]
  })
}

resource "aws_iam_role_policy_attachment" "ecs_execution" {
  role       = aws_iam_role.ecs_execution.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}

resource "aws_cloudwatch_log_group" "ecs" {
  name              = "/ecs/\${var.name}"
  retention_in_days = 30
}

resource "aws_security_group" "ecs" {
  name        = "\${var.name}-ecs-sg"
  description = "Security group for ECS tasks"
  vpc_id      = var.vpc_id

  ingress {
    from_port   = var.containerPort
    to_port     = var.containerPort
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

data "aws_region" "current" {}
`;
}

function generateElastiCacheModule(): string {
  return `# ElastiCache Module

resource "aws_elasticache_cluster" "this" {
  cluster_id           = var.clusterId
  engine               = var.engine
  node_type            = var.nodeType
  num_cache_nodes      = var.numCacheNodes
  port                 = var.port
  parameter_group_name = var.parameterGroupFamily == "redis7" ? "default.redis7" :
                         var.parameterGroupFamily == "redis6.x" ? "default.redis6.x" :
                         "default.memcached1.6"

  snapshot_retention_limit = var.snapshotRetention

  transit_encryption_enabled = var.transitEncryption
  at_rest_encryption_enabled = var.atRestEncryption

  tags = {
    Name = var.name
  }
}
`;
}

function generateIAMModule(): string {
  return `# IAM Role Module

resource "aws_iam_role" "this" {
  name        = var.roleName
  description = var.description

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = var.assumeRoleService
      }
    }]
  })

  max_session_duration = var.maxSessionDuration

  tags = {
    Name = var.name
  }
}

resource "aws_iam_role_policy_attachment" "managed_policies" {
  for_each   = toset(compact(split("\\n", var.managedPolicies)))
  role       = aws_iam_role.this.name
  policy_arn = each.value
}
`;
}

function generateRoute53Module(): string {
  return `# Route 53 Module

resource "aws_route53_zone" "this" {
  name    = var.domainName
  comment = var.comment

  dynamic "vpc" {
    for_each = var.zoneType == "private" ? [1] : []
    content {
      vpc_id = var.vpc_id
    }
  }

  tags = {
    Name = var.name
  }
}
`;
}

function generateModuleVariables(serviceId: string): string {
  const commonVars = `# Module Variables

variable "name" {
  description = "Resource name"
  type        = string
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "production"
}
`;

  const serviceVars = getServiceVariables(serviceId);
  return commonVars + '\n' + serviceVars;
}

function getServiceVariables(serviceId: string): string {
  // Return service-specific variables based on the properties in aws-services.ts
  const variableTemplates: Record<string, string> = {
    ec2: `
variable "instanceName" { type = string; default = "my-instance" }
variable "instanceType" { type = string; default = "t3.micro" }
variable "ami" { type = string; default = "amazon-linux-2023" }
variable "rootVolumeSize" { type = number; default = 30 }
variable "rootVolumeType" { type = string; default = "gp3" }
variable "publicIp" { type = bool; default = true }
variable "keyPair" { type = string; default = "" }
variable "monitoring" { type = bool; default = false }
`,
    lambda: `
variable "functionName" { type = string; default = "my-function" }
variable "runtime" { type = string; default = "nodejs20.x" }
variable "handler" { type = string; default = "index.handler" }
variable "memory" { type = number; default = 256 }
variable "timeout" { type = number; default = 30 }
variable "architecture" { type = string; default = "arm64" }
variable "reservedConcurrency" { type = number; default = -1 }
variable "envVars" { type = string; default = "" }
variable "enableTracing" { type = bool; default = false }
`,
    s3: `
variable "bucketName" { type = string }
variable "versioning" { type = bool; default = false }
variable "encryption" { type = string; default = "AES256" }
variable "publicAccess" { type = bool; default = true }
variable "staticHosting" { type = bool; default = false }
variable "indexDocument" { type = string; default = "index.html" }
variable "errorDocument" { type = string; default = "error.html" }
variable "lifecycleEnabled" { type = bool; default = false }
variable "transitionDays" { type = number; default = 30 }
variable "expirationDays" { type = number; default = 365 }
variable "enableCors" { type = bool; default = false }
`,
    rds: `
variable "identifier" { type = string }
variable "engine" { type = string; default = "postgres" }
variable "instanceClass" { type = string; default = "db.t3.micro" }
variable "allocatedStorage" { type = number; default = 20 }
variable "maxAllocatedStorage" { type = number; default = 100 }
variable "storageType" { type = string; default = "gp3" }
variable "dbName" { type = string; default = "mydb" }
variable "masterUsername" { type = string; default = "admin" }
variable "password" { type = string; sensitive = true }
variable "port" { type = number; default = 5432 }
variable "multiAz" { type = bool; default = false }
variable "publiclyAccessible" { type = bool; default = false }
variable "backupRetention" { type = number; default = 7 }
variable "deletionProtection" { type = bool; default = true }
variable "performanceInsights" { type = bool; default = false }
`,
    dynamodb: `
variable "tableName" { type = string }
variable "billingMode" { type = string; default = "PAY_PER_REQUEST" }
variable "hashKey" { type = string; default = "id" }
variable "hashKeyType" { type = string; default = "S" }
variable "rangeKey" { type = string; default = "" }
variable "rangeKeyType" { type = string; default = "S" }
variable "readCapacity" { type = number; default = 5 }
variable "writeCapacity" { type = number; default = 5 }
variable "enableStreams" { type = bool; default = false }
variable "streamViewType" { type = string; default = "NEW_AND_OLD_IMAGES" }
variable "ttlAttribute" { type = string; default = "" }
variable "pointInTimeRecovery" { type = bool; default = false }
`,
    'api-gateway': `
variable "apiName" { type = string }
variable "apiType" { type = string; default = "HTTP" }
variable "stageName" { type = string; default = "prod" }
variable "corsEnabled" { type = bool; default = true }
variable "corsOrigins" { type = string; default = "*" }
variable "throttlingBurstLimit" { type = number; default = 5000 }
variable "throttlingRateLimit" { type = number; default = 10000 }
variable "enableAccessLogs" { type = bool; default = false }
variable "enableXRay" { type = bool; default = false }
`,
    cloudfront: `
variable "comment" { type = string; default = "My Distribution" }
variable "priceClass" { type = string; default = "PriceClass_100" }
variable "defaultRootObject" { type = string; default = "index.html" }
variable "defaultTtl" { type = number; default = 86400 }
variable "maxTtl" { type = number; default = 31536000 }
variable "minTtl" { type = number; default = 0 }
variable "viewerProtocol" { type = string; default = "redirect-to-https" }
variable "enableCompression" { type = bool; default = true }
variable "enableWaf" { type = bool; default = false }
variable "enableLogging" { type = bool; default = false }
variable "origin_domain_name" { type = string }
`,
    sqs: `
variable "queueName" { type = string }
variable "fifoQueue" { type = bool; default = false }
variable "contentBasedDedup" { type = bool; default = false }
variable "visibilityTimeout" { type = number; default = 30 }
variable "messageRetention" { type = number; default = 345600 }
variable "maxMessageSize" { type = number; default = 262144 }
variable "delaySeconds" { type = number; default = 0 }
variable "receiveWaitTime" { type = number; default = 0 }
variable "enableDlq" { type = bool; default = false }
variable "maxReceiveCount" { type = number; default = 3 }
variable "enableEncryption" { type = bool; default = true }
`,
    sns: `
variable "topicName" { type = string }
variable "displayName" { type = string; default = "" }
variable "fifoTopic" { type = bool; default = false }
variable "contentBasedDedup" { type = bool; default = false }
variable "kmsMasterKeyId" { type = string; default = "" }
variable "deliveryPolicy" { type = number; default = 3 }
`,
    cognito: `
variable "poolName" { type = string }
variable "mfaConfiguration" { type = string; default = "OPTIONAL" }
variable "usernameAttributes" { type = string; default = "email" }
variable "autoVerifiedAttributes" { type = string; default = "email" }
variable "passwordMinLength" { type = number; default = 8 }
variable "passwordRequireUppercase" { type = bool; default = true }
variable "passwordRequireLowercase" { type = bool; default = true }
variable "passwordRequireNumbers" { type = bool; default = true }
variable "passwordRequireSymbols" { type = bool; default = true }
variable "allowAdminUserCreation" { type = bool; default = false }
variable "emailVerificationMessage" { type = string; default = "Your verification code is {####}" }
`,
    vpc: `
variable "vpcName" { type = string }
variable "cidrBlock" { type = string; default = "10.0.0.0/16" }
variable "enableDnsHostnames" { type = bool; default = true }
variable "enableDnsSupport" { type = bool; default = true }
variable "publicSubnets" { type = number; default = 2 }
variable "privateSubnets" { type = number; default = 2 }
variable "enableNatGateway" { type = bool; default = true }
variable "singleNatGateway" { type = bool; default = true }
variable "enableVpnGateway" { type = bool; default = false }
`,
    ecs: `
variable "clusterName" { type = string }
variable "serviceName" { type = string }
variable "launchType" { type = string; default = "FARGATE" }
variable "cpu" { type = string; default = "512" }
variable "memory" { type = string; default = "1024" }
variable "desiredCount" { type = number; default = 2 }
variable "containerPort" { type = number; default = 80 }
variable "healthCheckPath" { type = string; default = "/health" }
variable "enableAutoScaling" { type = bool; default = true }
variable "minCapacity" { type = number; default = 1 }
variable "maxCapacity" { type = number; default = 10 }
variable "vpc_id" { type = string; default = "" }
variable "subnet_ids" { type = list(string); default = [] }
`,
    elasticache: `
variable "clusterId" { type = string }
variable "engine" { type = string; default = "redis" }
variable "nodeType" { type = string; default = "cache.t3.micro" }
variable "numCacheNodes" { type = number; default = 1 }
variable "port" { type = number; default = 6379 }
variable "parameterGroupFamily" { type = string; default = "redis7" }
variable "snapshotRetention" { type = number; default = 0 }
variable "transitEncryption" { type = bool; default = true }
variable "atRestEncryption" { type = bool; default = true }
`,
    iam: `
variable "roleName" { type = string }
variable "description" { type = string; default = "" }
variable "assumeRoleService" { type = string; default = "lambda.amazonaws.com" }
variable "managedPolicies" { type = string; default = "" }
variable "maxSessionDuration" { type = number; default = 3600 }
`,
    route53: `
variable "domainName" { type = string }
variable "zoneType" { type = string; default = "public" }
variable "comment" { type = string; default = "" }
variable "vpc_id" { type = string; default = "" }
`,
    'vpc-environment': `
variable "vpcName" { type = string; default = "my-vpc" }
variable "cidrBlock" { type = string; default = "10.0.0.0/16" }
variable "enableDnsHostnames" { type = bool; default = true }
variable "enableDnsSupport" { type = bool; default = true }
`,
    'public-subnet': `
variable "subnetName" { type = string; default = "public-subnet" }
variable "cidrBlock" { type = string; default = "10.0.1.0/24" }
variable "availabilityZone" { type = string; default = "" }
variable "vpc_id" { type = string }
variable "public_route_table_id" { type = string }
`,
    'private-subnet': `
variable "subnetName" { type = string; default = "private-subnet" }
variable "cidrBlock" { type = string; default = "10.0.10.0/24" }
variable "availabilityZone" { type = string; default = "" }
variable "vpc_id" { type = string }
variable "nat_gateway_id" { type = string; default = "" }
`,
    alb: `
variable "albName" { type = string; default = "my-alb" }
variable "internal" { type = bool; default = false }
variable "idleTimeout" { type = number; default = 60 }
variable "enableHttp2" { type = bool; default = true }
variable "enableDeletionProtection" { type = bool; default = false }
variable "listenerPort" { type = number; default = 80 }
variable "targetPort" { type = number; default = 80 }
variable "healthCheckPath" { type = string; default = "/" }
variable "vpc_id" { type = string }
variable "subnet_ids" { type = list(string) }
`,
    nlb: `
variable "nlbName" { type = string; default = "my-nlb" }
variable "internal" { type = bool; default = false }
variable "enableCrossZone" { type = bool; default = true }
variable "listenerPort" { type = number; default = 80 }
variable "targetPort" { type = number; default = 80 }
variable "vpc_id" { type = string }
variable "subnet_ids" { type = list(string) }
`,
    'nat-gateway': `
variable "natName" { type = string; default = "my-nat" }
variable "connectivityType" { type = string; default = "public" }
variable "subnet_id" { type = string }
`,
  };

  return variableTemplates[serviceId] || '';
}

function generateModuleOutputs(serviceId: string): string {
  const outputTemplates: Record<string, string> = {
    ec2: `output "id" { value = aws_instance.this.id }
output "public_ip" { value = aws_instance.this.public_ip }
output "private_ip" { value = aws_instance.this.private_ip }`,
    lambda: `output "id" { value = aws_lambda_function.this.id }
output "arn" { value = aws_lambda_function.this.arn }
output "invoke_arn" { value = aws_lambda_function.this.invoke_arn }`,
    s3: `output "id" { value = aws_s3_bucket.this.id }
output "arn" { value = aws_s3_bucket.this.arn }
output "bucket_domain_name" { value = aws_s3_bucket.this.bucket_regional_domain_name }`,
    rds: `output "id" { value = aws_db_instance.this.id }
output "endpoint" { value = aws_db_instance.this.endpoint }
output "port" { value = aws_db_instance.this.port }`,
    dynamodb: `output "id" { value = aws_dynamodb_table.this.id }
output "arn" { value = aws_dynamodb_table.this.arn }`,
    'api-gateway': `output "id" { value = aws_apigatewayv2_api.this.id }
output "endpoint" { value = aws_apigatewayv2_stage.this.invoke_url }`,
    cloudfront: `output "id" { value = aws_cloudfront_distribution.this.id }
output "domain_name" { value = aws_cloudfront_distribution.this.domain_name }`,
    sqs: `output "id" { value = aws_sqs_queue.this.id }
output "arn" { value = aws_sqs_queue.this.arn }
output "url" { value = aws_sqs_queue.this.url }`,
    sns: `output "id" { value = aws_sns_topic.this.id }
output "arn" { value = aws_sns_topic.this.arn }`,
    cognito: `output "id" { value = aws_cognito_user_pool.this.id }
output "arn" { value = aws_cognito_user_pool.this.arn }
output "client_id" { value = aws_cognito_user_pool_client.this.id }`,
    vpc: `output "id" { value = aws_vpc.this.id }
output "public_subnet_ids" { value = aws_subnet.public[*].id }
output "private_subnet_ids" { value = aws_subnet.private[*].id }`,
    ecs: `output "id" { value = aws_ecs_cluster.this.id }
output "service_name" { value = aws_ecs_service.this.name }`,
    elasticache: `output "id" { value = aws_elasticache_cluster.this.id }
output "cache_nodes" { value = aws_elasticache_cluster.this.cache_nodes }`,
    iam: `output "id" { value = aws_iam_role.this.id }
output "arn" { value = aws_iam_role.this.arn }`,
    route53: `output "id" { value = aws_route53_zone.this.id }
output "name_servers" { value = aws_route53_zone.this.name_servers }`,
    'vpc-environment': `output "id" { value = aws_vpc.this.id }
output "cidr_block" { value = aws_vpc.this.cidr_block }
output "internet_gateway_id" { value = aws_internet_gateway.this.id }
output "public_route_table_id" { value = aws_route_table.public.id }`,
    'public-subnet': `output "id" { value = aws_subnet.this.id }
output "cidr_block" { value = aws_subnet.this.cidr_block }
output "availability_zone" { value = aws_subnet.this.availability_zone }`,
    'private-subnet': `output "id" { value = aws_subnet.this.id }
output "cidr_block" { value = aws_subnet.this.cidr_block }
output "availability_zone" { value = aws_subnet.this.availability_zone }
output "route_table_id" { value = aws_route_table.private.id }`,
    alb: `output "id" { value = aws_lb.this.id }
output "arn" { value = aws_lb.this.arn }
output "dns_name" { value = aws_lb.this.dns_name }
output "security_group_id" { value = aws_security_group.alb.id }
output "target_group_arn" { value = aws_lb_target_group.this.arn }`,
    nlb: `output "id" { value = aws_lb.this.id }
output "arn" { value = aws_lb.this.arn }
output "dns_name" { value = aws_lb.this.dns_name }
output "target_group_arn" { value = aws_lb_target_group.this.arn }`,
    'nat-gateway': `output "id" { value = aws_nat_gateway.this.id }
output "public_ip" { value = var.connectivityType == "public" ? aws_eip.this[0].public_ip : null }`,
  };

  return `# Module Outputs\n\n${outputTemplates[serviceId] || 'output "id" { value = "" }'}`;
}

// VPC Environment Module
function generateVpcEnvironmentModule(): string {
  return `# VPC Environment Module

resource "aws_vpc" "this" {
  cidr_block           = var.cidrBlock
  enable_dns_hostnames = var.enableDnsHostnames
  enable_dns_support   = var.enableDnsSupport

  tags = {
    Name        = var.vpcName
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

resource "aws_internet_gateway" "this" {
  vpc_id = aws_vpc.this.id

  tags = {
    Name        = "\${var.vpcName}-igw"
    Environment = var.environment
  }
}

resource "aws_route_table" "public" {
  vpc_id = aws_vpc.this.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.this.id
  }

  tags = {
    Name        = "\${var.vpcName}-public-rt"
    Environment = var.environment
    Type        = "public"
  }
}
`;
}

// Public Subnet Module
function generatePublicSubnetModule(): string {
  return `# Public Subnet Module

data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_subnet" "this" {
  vpc_id                  = var.vpc_id
  cidr_block              = var.cidrBlock
  availability_zone       = var.availabilityZone != "" ? var.availabilityZone : data.aws_availability_zones.available.names[0]
  map_public_ip_on_launch = true

  tags = {
    Name        = var.subnetName
    Environment = var.environment
    Type        = "public"
  }
}

resource "aws_route_table_association" "this" {
  subnet_id      = aws_subnet.this.id
  route_table_id = var.public_route_table_id
}
`;
}

// Private Subnet Module
function generatePrivateSubnetModule(): string {
  return `# Private Subnet Module

data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_subnet" "this" {
  vpc_id                  = var.vpc_id
  cidr_block              = var.cidrBlock
  availability_zone       = var.availabilityZone != "" ? var.availabilityZone : data.aws_availability_zones.available.names[0]
  map_public_ip_on_launch = false

  tags = {
    Name        = var.subnetName
    Environment = var.environment
    Type        = "private"
  }
}

resource "aws_route_table" "private" {
  vpc_id = var.vpc_id

  dynamic "route" {
    for_each = var.nat_gateway_id != "" ? [1] : []
    content {
      cidr_block     = "0.0.0.0/0"
      nat_gateway_id = var.nat_gateway_id
    }
  }

  tags = {
    Name        = "\${var.subnetName}-rt"
    Environment = var.environment
    Type        = "private"
  }
}

resource "aws_route_table_association" "this" {
  subnet_id      = aws_subnet.this.id
  route_table_id = aws_route_table.private.id
}
`;
}

// Application Load Balancer Module
function generateALBModule(): string {
  return `# Application Load Balancer Module

resource "aws_lb" "this" {
  name               = var.albName
  internal           = var.internal
  load_balancer_type = "application"
  security_groups    = [aws_security_group.alb.id]
  subnets            = var.subnet_ids

  enable_deletion_protection = var.enableDeletionProtection
  idle_timeout               = var.idleTimeout
  enable_http2               = var.enableHttp2

  tags = {
    Name        = var.albName
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

resource "aws_security_group" "alb" {
  name        = "\${var.albName}-sg"
  description = "Security group for Application Load Balancer"
  vpc_id      = var.vpc_id

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    description = "HTTP from internet"
  }

  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    description = "HTTPS from internet"
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
    description = "All outbound traffic"
  }

  tags = {
    Name        = "\${var.albName}-sg"
    Environment = var.environment
  }
}

resource "aws_lb_target_group" "this" {
  name        = "\${var.albName}-tg"
  port        = var.targetPort
  protocol    = "HTTP"
  vpc_id      = var.vpc_id
  target_type = "ip"

  health_check {
    enabled             = true
    healthy_threshold   = 2
    interval            = 30
    matcher             = "200-299"
    path                = var.healthCheckPath
    port                = "traffic-port"
    protocol            = "HTTP"
    timeout             = 5
    unhealthy_threshold = 2
  }

  tags = {
    Name        = "\${var.albName}-tg"
    Environment = var.environment
  }
}

resource "aws_lb_listener" "http" {
  load_balancer_arn = aws_lb.this.arn
  port              = var.listenerPort
  protocol          = "HTTP"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.this.arn
  }
}
`;
}

// Network Load Balancer Module
function generateNLBModule(): string {
  return `# Network Load Balancer Module

resource "aws_lb" "this" {
  name               = var.nlbName
  internal           = var.internal
  load_balancer_type = "network"
  subnets            = var.subnet_ids

  enable_cross_zone_load_balancing = var.enableCrossZone

  tags = {
    Name        = var.nlbName
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

resource "aws_lb_target_group" "this" {
  name        = "\${var.nlbName}-tg"
  port        = var.targetPort
  protocol    = "TCP"
  vpc_id      = var.vpc_id
  target_type = "ip"

  health_check {
    enabled             = true
    healthy_threshold   = 2
    interval            = 30
    port                = "traffic-port"
    protocol            = "TCP"
    unhealthy_threshold = 2
  }

  tags = {
    Name        = "\${var.nlbName}-tg"
    Environment = var.environment
  }
}

resource "aws_lb_listener" "this" {
  load_balancer_arn = aws_lb.this.arn
  port              = var.listenerPort
  protocol          = "TCP"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.this.arn
  }
}
`;
}

// NAT Gateway Module
function generateNatGatewayModule(): string {
  return `# NAT Gateway Module

resource "aws_eip" "this" {
  count  = var.connectivityType == "public" ? 1 : 0
  domain = "vpc"

  tags = {
    Name        = "\${var.natName}-eip"
    Environment = var.environment
  }
}

resource "aws_nat_gateway" "this" {
  allocation_id     = var.connectivityType == "public" ? aws_eip.this[0].id : null
  connectivity_type = var.connectivityType
  subnet_id         = var.subnet_id

  tags = {
    Name        = var.natName
    Environment = var.environment
    ManagedBy   = "terraform"
  }

  depends_on = [aws_eip.this]
}
`;
}

function generateReadme(nodes: Node<ServiceNodeData>[]): string {
  const services = nodes.map((n) => `- ${n.data.serviceName} (${n.data.serviceId})`).join('\n');

  return `# Infrastructure as Code - Generated by Archyra

## Overview

This Terraform configuration was generated by Archyra Architecture Designer.

## Resources

${services}

## Usage

1. Initialize Terraform:
   \`\`\`bash
   terraform init
   \`\`\`

2. Review the plan:
   \`\`\`bash
   terraform plan
   \`\`\`

3. Apply the configuration:
   \`\`\`bash
   terraform apply
   \`\`\`

## Structure

\`\`\`
├── main.tf           # Main configuration with module calls
├── variables.tf      # Input variables
├── outputs.tf        # Output values
├── README.md         # This file
└── modules/          # Reusable modules
    ├── ec2/
    ├── s3/
    ├── rds/
    └── ...
\`\`\`

## Important Notes

- Review and customize the generated code before deploying
- Set sensitive values (passwords, keys) using environment variables or secrets manager
- Consider using remote state storage for team collaboration

## Generated

Date: ${new Date().toISOString()}
Tool: Archyra Architecture Designer
`;
}
