// AWS Service definitions for the Architecture Designer

export interface ServiceProperty {
  name: string;
  label: string;
  type: 'text' | 'select' | 'number' | 'boolean' | 'textarea';
  default: string | number | boolean;
  options?: { value: string; label: string }[];
  description?: string;
  required?: boolean;
}

// Subnet placement rules for services
export interface SubnetPlacement {
  allowedInPublic: boolean;
  allowedInPrivate: boolean;
  requiresSubnet: boolean;
}

export interface AWSService {
  id: string;
  name: string;
  shortName: string;
  category: 'compute' | 'storage' | 'database' | 'networking' | 'security' | 'integration';
  description: string;
  color: string;
  icon: string;
  allowedConnections: string[];
  properties: ServiceProperty[];
  terraformResource: string;
  pulumiClass: string;
  // Container and nesting support
  isContainer?: boolean;
  parentRequired?: string;
  subnetPlacement?: SubnetPlacement;
}

export const serviceCategories = [
  { id: 'compute', name: 'Compute', color: '#FF9900' },
  { id: 'storage', name: 'Storage', color: '#569A31' },
  { id: 'database', name: 'Database', color: '#4053D6' },
  { id: 'networking', name: 'Networking', color: '#8C4FFF' },
  { id: 'security', name: 'Security', color: '#DD344C' },
  { id: 'integration', name: 'Integration', color: '#FF4F8B' },
] as const;

export const awsServices: AWSService[] = [
  // Compute
  {
    id: 'ec2',
    name: 'EC2',
    shortName: 'EC2',
    category: 'compute',
    description: 'Virtual servers in the cloud',
    color: '#FF9900',
    icon: 'server',
    allowedConnections: ['rds', 'dynamodb', 's3', 'elasticache', 'sqs', 'sns', 'vpc', 'iam'],
    properties: [
      {
        name: 'instanceName',
        label: 'Instance Name',
        type: 'text',
        default: 'my-instance',
        description: 'Name tag for the instance',
        required: true,
      },
      {
        name: 'instanceType',
        label: 'Instance Type',
        type: 'select',
        default: 't3.micro',
        options: [
          { value: 't3.micro', label: 't3.micro (Free tier)' },
          { value: 't3.small', label: 't3.small (2 vCPU, 2GB)' },
          { value: 't3.medium', label: 't3.medium (2 vCPU, 4GB)' },
          { value: 't3.large', label: 't3.large (2 vCPU, 8GB)' },
          { value: 'm5.large', label: 'm5.large (2 vCPU, 8GB)' },
          { value: 'm5.xlarge', label: 'm5.xlarge (4 vCPU, 16GB)' },
          { value: 'c5.large', label: 'c5.large (Compute optimized)' },
          { value: 'r5.large', label: 'r5.large (Memory optimized)' },
        ],
      },
      {
        name: 'ami',
        label: 'Operating System',
        type: 'select',
        default: 'amazon-linux-2023',
        options: [
          { value: 'amazon-linux-2023', label: 'Amazon Linux 2023' },
          { value: 'amazon-linux-2', label: 'Amazon Linux 2' },
          { value: 'ubuntu-24', label: 'Ubuntu 24.04 LTS' },
          { value: 'ubuntu-22', label: 'Ubuntu 22.04 LTS' },
          { value: 'debian-12', label: 'Debian 12' },
          { value: 'windows-2022', label: 'Windows Server 2022' },
          { value: 'windows-2019', label: 'Windows Server 2019' },
        ],
      },
      {
        name: 'rootVolumeSize',
        label: 'Root Volume Size (GB)',
        type: 'number',
        default: 30,
        description: 'Size of the root EBS volume',
      },
      {
        name: 'rootVolumeType',
        label: 'Volume Type',
        type: 'select',
        default: 'gp3',
        options: [
          { value: 'gp3', label: 'GP3 (General Purpose SSD)' },
          { value: 'gp2', label: 'GP2 (General Purpose SSD)' },
          { value: 'io1', label: 'IO1 (Provisioned IOPS)' },
          { value: 'st1', label: 'ST1 (Throughput Optimized HDD)' },
        ],
      },
      {
        name: 'publicIp',
        label: 'Associate Public IP',
        type: 'boolean',
        default: true,
        description: 'Assign a public IP address',
      },
      {
        name: 'keyPair',
        label: 'Key Pair Name',
        type: 'text',
        default: '',
        description: 'SSH key pair for access',
      },
      {
        name: 'monitoring',
        label: 'Detailed Monitoring',
        type: 'boolean',
        default: false,
        description: 'Enable detailed CloudWatch monitoring',
      },
    ],
    terraformResource: 'aws_instance',
    pulumiClass: 'aws.ec2.Instance',
    subnetPlacement: {
      allowedInPublic: true,
      allowedInPrivate: true,
      requiresSubnet: false,
    },
  },
  {
    id: 'lambda',
    name: 'Lambda',
    shortName: 'λ',
    category: 'compute',
    description: 'Serverless compute service',
    color: '#FF9900',
    icon: 'zap',
    allowedConnections: ['dynamodb', 's3', 'rds', 'sqs', 'sns', 'api-gateway', 'iam', 'vpc', 'cloudfront', 'elasticache', 'cognito'],
    properties: [
      {
        name: 'functionName',
        label: 'Function Name',
        type: 'text',
        default: 'my-function',
        required: true,
      },
      {
        name: 'runtime',
        label: 'Runtime',
        type: 'select',
        default: 'nodejs20.x',
        options: [
          { value: 'nodejs20.x', label: 'Node.js 20.x' },
          { value: 'nodejs18.x', label: 'Node.js 18.x' },
          { value: 'python3.12', label: 'Python 3.12' },
          { value: 'python3.11', label: 'Python 3.11' },
          { value: 'python3.10', label: 'Python 3.10' },
          { value: 'java21', label: 'Java 21 (Corretto)' },
          { value: 'java17', label: 'Java 17 (Corretto)' },
          { value: 'go1.x', label: 'Go 1.x' },
          { value: 'dotnet8', label: '.NET 8' },
          { value: 'ruby3.3', label: 'Ruby 3.3' },
        ],
      },
      {
        name: 'handler',
        label: 'Handler',
        type: 'text',
        default: 'index.handler',
        description: 'Function entry point',
      },
      {
        name: 'memory',
        label: 'Memory (MB)',
        type: 'select',
        default: '256',
        options: [
          { value: '128', label: '128 MB' },
          { value: '256', label: '256 MB' },
          { value: '512', label: '512 MB' },
          { value: '1024', label: '1 GB' },
          { value: '2048', label: '2 GB' },
          { value: '3072', label: '3 GB' },
          { value: '4096', label: '4 GB' },
          { value: '8192', label: '8 GB' },
          { value: '10240', label: '10 GB' },
        ],
      },
      {
        name: 'timeout',
        label: 'Timeout (seconds)',
        type: 'number',
        default: 30,
        description: 'Max execution time (1-900)',
      },
      {
        name: 'architecture',
        label: 'Architecture',
        type: 'select',
        default: 'arm64',
        options: [
          { value: 'arm64', label: 'ARM64 (Graviton2)' },
          { value: 'x86_64', label: 'x86_64' },
        ],
      },
      {
        name: 'reservedConcurrency',
        label: 'Reserved Concurrency',
        type: 'number',
        default: -1,
        description: '-1 for unreserved',
      },
      {
        name: 'envVars',
        label: 'Environment Variables',
        type: 'textarea',
        default: '',
        description: 'KEY=value, one per line',
      },
      {
        name: 'enableTracing',
        label: 'X-Ray Tracing',
        type: 'boolean',
        default: false,
      },
    ],
    terraformResource: 'aws_lambda_function',
    pulumiClass: 'aws.lambda.Function',
    subnetPlacement: {
      allowedInPublic: true,
      allowedInPrivate: true,
      requiresSubnet: false,
    },
  },
  {
    id: 'ecs',
    name: 'ECS',
    shortName: 'ECS',
    category: 'compute',
    description: 'Container orchestration service',
    color: '#FF9900',
    icon: 'container',
    allowedConnections: ['rds', 'dynamodb', 's3', 'elasticache', 'sqs', 'sns', 'vpc', 'iam'],
    properties: [
      {
        name: 'clusterName',
        label: 'Cluster Name',
        type: 'text',
        default: 'my-cluster',
        required: true,
      },
      {
        name: 'serviceName',
        label: 'Service Name',
        type: 'text',
        default: 'my-service',
        required: true,
      },
      {
        name: 'launchType',
        label: 'Launch Type',
        type: 'select',
        default: 'FARGATE',
        options: [
          { value: 'FARGATE', label: 'Fargate (Serverless)' },
          { value: 'EC2', label: 'EC2' },
          { value: 'FARGATE_SPOT', label: 'Fargate Spot' },
        ],
      },
      {
        name: 'cpu',
        label: 'CPU',
        type: 'select',
        default: '512',
        options: [
          { value: '256', label: '0.25 vCPU' },
          { value: '512', label: '0.5 vCPU' },
          { value: '1024', label: '1 vCPU' },
          { value: '2048', label: '2 vCPU' },
          { value: '4096', label: '4 vCPU' },
        ],
      },
      {
        name: 'memory',
        label: 'Memory',
        type: 'select',
        default: '1024',
        options: [
          { value: '512', label: '512 MB' },
          { value: '1024', label: '1 GB' },
          { value: '2048', label: '2 GB' },
          { value: '4096', label: '4 GB' },
          { value: '8192', label: '8 GB' },
          { value: '16384', label: '16 GB' },
        ],
      },
      {
        name: 'desiredCount',
        label: 'Desired Tasks',
        type: 'number',
        default: 2,
        description: 'Number of task instances',
      },
      {
        name: 'containerPort',
        label: 'Container Port',
        type: 'number',
        default: 80,
      },
      {
        name: 'healthCheckPath',
        label: 'Health Check Path',
        type: 'text',
        default: '/health',
      },
      {
        name: 'enableAutoScaling',
        label: 'Enable Auto Scaling',
        type: 'boolean',
        default: true,
      },
      {
        name: 'minCapacity',
        label: 'Min Tasks',
        type: 'number',
        default: 1,
      },
      {
        name: 'maxCapacity',
        label: 'Max Tasks',
        type: 'number',
        default: 10,
      },
    ],
    terraformResource: 'aws_ecs_service',
    pulumiClass: 'aws.ecs.Service',
    subnetPlacement: {
      allowedInPublic: true,
      allowedInPrivate: true,
      requiresSubnet: false,
    },
  },

  // Storage
  {
    id: 's3',
    name: 'S3',
    shortName: 'S3',
    category: 'storage',
    description: 'Object storage service',
    color: '#569A31',
    icon: 'database',
    allowedConnections: ['cloudfront', 'lambda', 'iam'],
    properties: [
      {
        name: 'bucketName',
        label: 'Bucket Name',
        type: 'text',
        default: 'my-bucket',
        description: 'Globally unique bucket name',
        required: true,
      },
      {
        name: 'versioning',
        label: 'Versioning',
        type: 'boolean',
        default: false,
        description: 'Enable object versioning',
      },
      {
        name: 'encryption',
        label: 'Encryption',
        type: 'select',
        default: 'AES256',
        options: [
          { value: 'AES256', label: 'SSE-S3 (AES-256)' },
          { value: 'aws:kms', label: 'SSE-KMS' },
          { value: 'none', label: 'None' },
        ],
      },
      {
        name: 'publicAccess',
        label: 'Block Public Access',
        type: 'boolean',
        default: true,
        description: 'Block all public access',
      },
      {
        name: 'staticHosting',
        label: 'Static Website Hosting',
        type: 'boolean',
        default: false,
      },
      {
        name: 'indexDocument',
        label: 'Index Document',
        type: 'text',
        default: 'index.html',
        description: 'For static hosting',
      },
      {
        name: 'errorDocument',
        label: 'Error Document',
        type: 'text',
        default: 'error.html',
        description: 'For static hosting',
      },
      {
        name: 'lifecycleEnabled',
        label: 'Lifecycle Rules',
        type: 'boolean',
        default: false,
      },
      {
        name: 'transitionDays',
        label: 'Transition to IA (days)',
        type: 'number',
        default: 30,
        description: 'Days before moving to Infrequent Access',
      },
      {
        name: 'expirationDays',
        label: 'Expiration (days)',
        type: 'number',
        default: 365,
        description: '0 to disable',
      },
      {
        name: 'enableCors',
        label: 'Enable CORS',
        type: 'boolean',
        default: false,
      },
    ],
    terraformResource: 'aws_s3_bucket',
    pulumiClass: 'aws.s3.Bucket',
  },

  // Database
  {
    id: 'rds',
    name: 'RDS',
    shortName: 'RDS',
    category: 'database',
    description: 'Managed relational database',
    color: '#4053D6',
    icon: 'database',
    allowedConnections: ['ec2', 'lambda', 'ecs', 'vpc'],
    properties: [
      {
        name: 'identifier',
        label: 'DB Identifier',
        type: 'text',
        default: 'my-database',
        required: true,
      },
      {
        name: 'engine',
        label: 'Database Engine',
        type: 'select',
        default: 'postgres',
        options: [
          { value: 'postgres', label: 'PostgreSQL 16' },
          { value: 'mysql', label: 'MySQL 8.0' },
          { value: 'mariadb', label: 'MariaDB 10.11' },
          { value: 'aurora-postgresql', label: 'Aurora PostgreSQL' },
          { value: 'aurora-mysql', label: 'Aurora MySQL' },
          { value: 'sqlserver-ex', label: 'SQL Server Express' },
          { value: 'oracle-se2', label: 'Oracle SE2' },
        ],
      },
      {
        name: 'instanceClass',
        label: 'Instance Class',
        type: 'select',
        default: 'db.t3.micro',
        options: [
          { value: 'db.t3.micro', label: 'db.t3.micro (Free tier)' },
          { value: 'db.t3.small', label: 'db.t3.small (2 vCPU, 2GB)' },
          { value: 'db.t3.medium', label: 'db.t3.medium (2 vCPU, 4GB)' },
          { value: 'db.t3.large', label: 'db.t3.large (2 vCPU, 8GB)' },
          { value: 'db.r5.large', label: 'db.r5.large (2 vCPU, 16GB)' },
          { value: 'db.r5.xlarge', label: 'db.r5.xlarge (4 vCPU, 32GB)' },
          { value: 'db.m5.large', label: 'db.m5.large (2 vCPU, 8GB)' },
        ],
      },
      {
        name: 'allocatedStorage',
        label: 'Storage (GB)',
        type: 'number',
        default: 20,
      },
      {
        name: 'maxAllocatedStorage',
        label: 'Max Storage (GB)',
        type: 'number',
        default: 100,
        description: 'For storage autoscaling',
      },
      {
        name: 'storageType',
        label: 'Storage Type',
        type: 'select',
        default: 'gp3',
        options: [
          { value: 'gp3', label: 'General Purpose SSD (gp3)' },
          { value: 'gp2', label: 'General Purpose SSD (gp2)' },
          { value: 'io1', label: 'Provisioned IOPS (io1)' },
        ],
      },
      {
        name: 'dbName',
        label: 'Database Name',
        type: 'text',
        default: 'mydb',
      },
      {
        name: 'masterUsername',
        label: 'Master Username',
        type: 'text',
        default: 'admin',
      },
      {
        name: 'port',
        label: 'Port',
        type: 'number',
        default: 5432,
      },
      {
        name: 'multiAz',
        label: 'Multi-AZ Deployment',
        type: 'boolean',
        default: false,
        description: 'High availability',
      },
      {
        name: 'publiclyAccessible',
        label: 'Publicly Accessible',
        type: 'boolean',
        default: false,
      },
      {
        name: 'backupRetention',
        label: 'Backup Retention (days)',
        type: 'number',
        default: 7,
      },
      {
        name: 'deletionProtection',
        label: 'Deletion Protection',
        type: 'boolean',
        default: true,
      },
      {
        name: 'performanceInsights',
        label: 'Performance Insights',
        type: 'boolean',
        default: false,
      },
    ],
    terraformResource: 'aws_db_instance',
    pulumiClass: 'aws.rds.Instance',
    subnetPlacement: {
      allowedInPublic: false,
      allowedInPrivate: true,
      requiresSubnet: false,
    },
  },
  {
    id: 'dynamodb',
    name: 'DynamoDB',
    shortName: 'DDB',
    category: 'database',
    description: 'NoSQL database service',
    color: '#4053D6',
    icon: 'table',
    allowedConnections: ['lambda', 'ec2', 'ecs', 'iam'],
    properties: [
      {
        name: 'tableName',
        label: 'Table Name',
        type: 'text',
        default: 'my-table',
        required: true,
      },
      {
        name: 'billingMode',
        label: 'Billing Mode',
        type: 'select',
        default: 'PAY_PER_REQUEST',
        options: [
          { value: 'PAY_PER_REQUEST', label: 'On-Demand' },
          { value: 'PROVISIONED', label: 'Provisioned' },
        ],
      },
      {
        name: 'hashKey',
        label: 'Partition Key',
        type: 'text',
        default: 'id',
        required: true,
      },
      {
        name: 'hashKeyType',
        label: 'Partition Key Type',
        type: 'select',
        default: 'S',
        options: [
          { value: 'S', label: 'String' },
          { value: 'N', label: 'Number' },
          { value: 'B', label: 'Binary' },
        ],
      },
      {
        name: 'rangeKey',
        label: 'Sort Key (optional)',
        type: 'text',
        default: '',
      },
      {
        name: 'rangeKeyType',
        label: 'Sort Key Type',
        type: 'select',
        default: 'S',
        options: [
          { value: 'S', label: 'String' },
          { value: 'N', label: 'Number' },
          { value: 'B', label: 'Binary' },
        ],
      },
      {
        name: 'readCapacity',
        label: 'Read Capacity Units',
        type: 'number',
        default: 5,
        description: 'For provisioned mode',
      },
      {
        name: 'writeCapacity',
        label: 'Write Capacity Units',
        type: 'number',
        default: 5,
        description: 'For provisioned mode',
      },
      {
        name: 'enableStreams',
        label: 'Enable Streams',
        type: 'boolean',
        default: false,
      },
      {
        name: 'streamViewType',
        label: 'Stream View Type',
        type: 'select',
        default: 'NEW_AND_OLD_IMAGES',
        options: [
          { value: 'NEW_AND_OLD_IMAGES', label: 'New and Old Images' },
          { value: 'NEW_IMAGE', label: 'New Image Only' },
          { value: 'OLD_IMAGE', label: 'Old Image Only' },
          { value: 'KEYS_ONLY', label: 'Keys Only' },
        ],
      },
      {
        name: 'ttlAttribute',
        label: 'TTL Attribute',
        type: 'text',
        default: '',
        description: 'Leave empty to disable TTL',
      },
      {
        name: 'pointInTimeRecovery',
        label: 'Point-in-Time Recovery',
        type: 'boolean',
        default: false,
      },
    ],
    terraformResource: 'aws_dynamodb_table',
    pulumiClass: 'aws.dynamodb.Table',
  },
  {
    id: 'elasticache',
    name: 'ElastiCache',
    shortName: 'Cache',
    category: 'database',
    description: 'In-memory caching service',
    color: '#4053D6',
    icon: 'zap',
    allowedConnections: ['ec2', 'lambda', 'ecs', 'vpc'],
    properties: [
      {
        name: 'clusterId',
        label: 'Cluster ID',
        type: 'text',
        default: 'my-cache',
        required: true,
      },
      {
        name: 'engine',
        label: 'Engine',
        type: 'select',
        default: 'redis',
        options: [
          { value: 'redis', label: 'Redis 7.x' },
          { value: 'memcached', label: 'Memcached 1.6' },
        ],
      },
      {
        name: 'nodeType',
        label: 'Node Type',
        type: 'select',
        default: 'cache.t3.micro',
        options: [
          { value: 'cache.t3.micro', label: 'cache.t3.micro (0.5GB)' },
          { value: 'cache.t3.small', label: 'cache.t3.small (1.5GB)' },
          { value: 'cache.t3.medium', label: 'cache.t3.medium (3GB)' },
          { value: 'cache.r5.large', label: 'cache.r5.large (13GB)' },
          { value: 'cache.r5.xlarge', label: 'cache.r5.xlarge (26GB)' },
        ],
      },
      {
        name: 'numCacheNodes',
        label: 'Number of Nodes',
        type: 'number',
        default: 1,
      },
      {
        name: 'port',
        label: 'Port',
        type: 'number',
        default: 6379,
      },
      {
        name: 'parameterGroupFamily',
        label: 'Parameter Group',
        type: 'select',
        default: 'redis7',
        options: [
          { value: 'redis7', label: 'redis7' },
          { value: 'redis6.x', label: 'redis6.x' },
          { value: 'memcached1.6', label: 'memcached1.6' },
        ],
      },
      {
        name: 'snapshotRetention',
        label: 'Snapshot Retention (days)',
        type: 'number',
        default: 0,
        description: '0 to disable',
      },
      {
        name: 'transitEncryption',
        label: 'Transit Encryption (TLS)',
        type: 'boolean',
        default: true,
      },
      {
        name: 'atRestEncryption',
        label: 'At-Rest Encryption',
        type: 'boolean',
        default: true,
      },
    ],
    terraformResource: 'aws_elasticache_cluster',
    pulumiClass: 'aws.elasticache.Cluster',
    subnetPlacement: {
      allowedInPublic: false,
      allowedInPrivate: true,
      requiresSubnet: false,
    },
  },

  // Networking
  {
    id: 'cloudfront',
    name: 'CloudFront',
    shortName: 'CF',
    category: 'networking',
    description: 'Content delivery network',
    color: '#8C4FFF',
    icon: 'globe',
    allowedConnections: ['s3', 'api-gateway', 'ec2', 'lambda', 'route53', 'alb', 'nlb'],
    properties: [
      {
        name: 'comment',
        label: 'Distribution Name',
        type: 'text',
        default: 'My Distribution',
      },
      {
        name: 'priceClass',
        label: 'Price Class',
        type: 'select',
        default: 'PriceClass_100',
        options: [
          { value: 'PriceClass_100', label: 'North America & Europe' },
          { value: 'PriceClass_200', label: 'NA, EU, Asia, Middle East, Africa' },
          { value: 'PriceClass_All', label: 'All Edge Locations (Global)' },
        ],
      },
      {
        name: 'defaultRootObject',
        label: 'Default Root Object',
        type: 'text',
        default: 'index.html',
      },
      {
        name: 'defaultTtl',
        label: 'Default TTL (seconds)',
        type: 'number',
        default: 86400,
      },
      {
        name: 'maxTtl',
        label: 'Max TTL (seconds)',
        type: 'number',
        default: 31536000,
      },
      {
        name: 'minTtl',
        label: 'Min TTL (seconds)',
        type: 'number',
        default: 0,
      },
      {
        name: 'viewerProtocol',
        label: 'Viewer Protocol Policy',
        type: 'select',
        default: 'redirect-to-https',
        options: [
          { value: 'redirect-to-https', label: 'Redirect HTTP to HTTPS' },
          { value: 'https-only', label: 'HTTPS Only' },
          { value: 'allow-all', label: 'HTTP and HTTPS' },
        ],
      },
      {
        name: 'enableCompression',
        label: 'Enable Compression',
        type: 'boolean',
        default: true,
      },
      {
        name: 'enableWaf',
        label: 'Enable WAF',
        type: 'boolean',
        default: false,
      },
      {
        name: 'enableLogging',
        label: 'Enable Access Logging',
        type: 'boolean',
        default: false,
      },
    ],
    terraformResource: 'aws_cloudfront_distribution',
    pulumiClass: 'aws.cloudfront.Distribution',
  },
  {
    id: 'route53',
    name: 'Route 53',
    shortName: 'R53',
    category: 'networking',
    description: 'DNS and domain management',
    color: '#8C4FFF',
    icon: 'globe',
    allowedConnections: ['cloudfront', 'api-gateway', 'ec2', 's3'],
    properties: [
      {
        name: 'domainName',
        label: 'Domain Name',
        type: 'text',
        default: 'example.com',
        required: true,
      },
      {
        name: 'zoneType',
        label: 'Zone Type',
        type: 'select',
        default: 'public',
        options: [
          { value: 'public', label: 'Public Hosted Zone' },
          { value: 'private', label: 'Private Hosted Zone' },
        ],
      },
      {
        name: 'comment',
        label: 'Description',
        type: 'text',
        default: '',
      },
    ],
    terraformResource: 'aws_route53_zone',
    pulumiClass: 'aws.route53.Zone',
  },
  {
    id: 'vpc',
    name: 'VPC',
    shortName: 'VPC',
    category: 'networking',
    description: 'Virtual private cloud',
    color: '#8C4FFF',
    icon: 'network',
    allowedConnections: ['ec2', 'rds', 'ecs', 'lambda', 'elasticache'],
    properties: [
      {
        name: 'vpcName',
        label: 'VPC Name',
        type: 'text',
        default: 'my-vpc',
        required: true,
      },
      {
        name: 'cidrBlock',
        label: 'CIDR Block',
        type: 'text',
        default: '10.0.0.0/16',
        required: true,
      },
      {
        name: 'enableDnsHostnames',
        label: 'DNS Hostnames',
        type: 'boolean',
        default: true,
      },
      {
        name: 'enableDnsSupport',
        label: 'DNS Support',
        type: 'boolean',
        default: true,
      },
      {
        name: 'publicSubnets',
        label: 'Public Subnets',
        type: 'number',
        default: 2,
        description: 'Number of public subnets',
      },
      {
        name: 'privateSubnets',
        label: 'Private Subnets',
        type: 'number',
        default: 2,
        description: 'Number of private subnets',
      },
      {
        name: 'enableNatGateway',
        label: 'NAT Gateway',
        type: 'boolean',
        default: true,
        description: 'For private subnet internet access',
      },
      {
        name: 'singleNatGateway',
        label: 'Single NAT Gateway',
        type: 'boolean',
        default: true,
        description: 'Use one NAT for all AZs (cost saving)',
      },
      {
        name: 'enableVpnGateway',
        label: 'VPN Gateway',
        type: 'boolean',
        default: false,
      },
    ],
    terraformResource: 'aws_vpc',
    pulumiClass: 'aws.ec2.Vpc',
  },
  {
    id: 'api-gateway',
    name: 'API Gateway',
    shortName: 'API',
    category: 'networking',
    description: 'API management service',
    color: '#FF4F8B',
    icon: 'git-branch',
    allowedConnections: ['lambda', 'ec2', 'ecs', 'cognito'],
    properties: [
      {
        name: 'apiName',
        label: 'API Name',
        type: 'text',
        default: 'my-api',
        required: true,
      },
      {
        name: 'apiType',
        label: 'API Type',
        type: 'select',
        default: 'HTTP',
        options: [
          { value: 'HTTP', label: 'HTTP API (Recommended)' },
          { value: 'REST', label: 'REST API' },
          { value: 'WEBSOCKET', label: 'WebSocket API' },
        ],
      },
      {
        name: 'stageName',
        label: 'Stage Name',
        type: 'text',
        default: 'prod',
      },
      {
        name: 'corsEnabled',
        label: 'Enable CORS',
        type: 'boolean',
        default: true,
      },
      {
        name: 'corsOrigins',
        label: 'CORS Origins',
        type: 'text',
        default: '*',
        description: 'Comma-separated origins',
      },
      {
        name: 'throttlingBurstLimit',
        label: 'Throttling Burst Limit',
        type: 'number',
        default: 5000,
      },
      {
        name: 'throttlingRateLimit',
        label: 'Throttling Rate Limit',
        type: 'number',
        default: 10000,
      },
      {
        name: 'enableAccessLogs',
        label: 'Enable Access Logs',
        type: 'boolean',
        default: false,
      },
      {
        name: 'enableXRay',
        label: 'Enable X-Ray Tracing',
        type: 'boolean',
        default: false,
      },
    ],
    terraformResource: 'aws_apigatewayv2_api',
    pulumiClass: 'aws.apigatewayv2.Api',
  },

  // Security
  {
    id: 'iam',
    name: 'IAM Role',
    shortName: 'IAM',
    category: 'security',
    description: 'Identity and access management',
    color: '#DD344C',
    icon: 'shield',
    allowedConnections: ['lambda', 'ec2', 'ecs', 's3', 'dynamodb'],
    properties: [
      {
        name: 'roleName',
        label: 'Role Name',
        type: 'text',
        default: 'my-role',
        required: true,
      },
      {
        name: 'description',
        label: 'Description',
        type: 'text',
        default: '',
      },
      {
        name: 'assumeRoleService',
        label: 'Trusted Service',
        type: 'select',
        default: 'lambda.amazonaws.com',
        options: [
          { value: 'lambda.amazonaws.com', label: 'Lambda' },
          { value: 'ec2.amazonaws.com', label: 'EC2' },
          { value: 'ecs-tasks.amazonaws.com', label: 'ECS Tasks' },
          { value: 'apigateway.amazonaws.com', label: 'API Gateway' },
          { value: 'states.amazonaws.com', label: 'Step Functions' },
        ],
      },
      {
        name: 'managedPolicies',
        label: 'Managed Policies',
        type: 'textarea',
        default: 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
        description: 'One ARN per line',
      },
      {
        name: 'maxSessionDuration',
        label: 'Max Session Duration (seconds)',
        type: 'number',
        default: 3600,
      },
    ],
    terraformResource: 'aws_iam_role',
    pulumiClass: 'aws.iam.Role',
  },
  {
    id: 'cognito',
    name: 'Cognito',
    shortName: 'Cog',
    category: 'security',
    description: 'User authentication service',
    color: '#DD344C',
    icon: 'users',
    allowedConnections: ['api-gateway', 'lambda'],
    properties: [
      {
        name: 'poolName',
        label: 'User Pool Name',
        type: 'text',
        default: 'my-user-pool',
        required: true,
      },
      {
        name: 'mfaConfiguration',
        label: 'MFA',
        type: 'select',
        default: 'OPTIONAL',
        options: [
          { value: 'OFF', label: 'Off' },
          { value: 'OPTIONAL', label: 'Optional' },
          { value: 'ON', label: 'Required' },
        ],
      },
      {
        name: 'usernameAttributes',
        label: 'Sign-in Method',
        type: 'select',
        default: 'email',
        options: [
          { value: 'email', label: 'Email' },
          { value: 'phone_number', label: 'Phone Number' },
          { value: 'preferred_username', label: 'Username' },
        ],
      },
      {
        name: 'autoVerifiedAttributes',
        label: 'Auto-verify',
        type: 'select',
        default: 'email',
        options: [
          { value: 'email', label: 'Email' },
          { value: 'phone_number', label: 'Phone Number' },
        ],
      },
      {
        name: 'passwordMinLength',
        label: 'Min Password Length',
        type: 'number',
        default: 8,
      },
      {
        name: 'passwordRequireUppercase',
        label: 'Require Uppercase',
        type: 'boolean',
        default: true,
      },
      {
        name: 'passwordRequireLowercase',
        label: 'Require Lowercase',
        type: 'boolean',
        default: true,
      },
      {
        name: 'passwordRequireNumbers',
        label: 'Require Numbers',
        type: 'boolean',
        default: true,
      },
      {
        name: 'passwordRequireSymbols',
        label: 'Require Symbols',
        type: 'boolean',
        default: true,
      },
      {
        name: 'allowAdminUserCreation',
        label: 'Admin Create Users Only',
        type: 'boolean',
        default: false,
      },
      {
        name: 'emailVerificationMessage',
        label: 'Email Verification Message',
        type: 'textarea',
        default: 'Your verification code is {####}',
      },
    ],
    terraformResource: 'aws_cognito_user_pool',
    pulumiClass: 'aws.cognito.UserPool',
  },

  // Integration
  {
    id: 'sns',
    name: 'SNS',
    shortName: 'SNS',
    category: 'integration',
    description: 'Pub/sub messaging service',
    color: '#FF4F8B',
    icon: 'bell',
    allowedConnections: ['lambda', 'sqs'],
    properties: [
      {
        name: 'topicName',
        label: 'Topic Name',
        type: 'text',
        default: 'my-topic',
        required: true,
      },
      {
        name: 'displayName',
        label: 'Display Name',
        type: 'text',
        default: '',
        description: 'For SMS subscriptions',
      },
      {
        name: 'fifoTopic',
        label: 'FIFO Topic',
        type: 'boolean',
        default: false,
      },
      {
        name: 'contentBasedDedup',
        label: 'Content-based Deduplication',
        type: 'boolean',
        default: false,
        description: 'For FIFO topics',
      },
      {
        name: 'kmsMasterKeyId',
        label: 'KMS Key ID',
        type: 'text',
        default: '',
        description: 'For encryption',
      },
      {
        name: 'deliveryPolicy',
        label: 'HTTP Retry Count',
        type: 'number',
        default: 3,
      },
    ],
    terraformResource: 'aws_sns_topic',
    pulumiClass: 'aws.sns.Topic',
  },
  {
    id: 'sqs',
    name: 'SQS',
    shortName: 'SQS',
    category: 'integration',
    description: 'Message queue service',
    color: '#FF4F8B',
    icon: 'inbox',
    allowedConnections: ['lambda', 'ec2', 'ecs', 'sns'],
    properties: [
      {
        name: 'queueName',
        label: 'Queue Name',
        type: 'text',
        default: 'my-queue',
        required: true,
      },
      {
        name: 'fifoQueue',
        label: 'FIFO Queue',
        type: 'boolean',
        default: false,
      },
      {
        name: 'contentBasedDedup',
        label: 'Content-based Deduplication',
        type: 'boolean',
        default: false,
        description: 'For FIFO queues',
      },
      {
        name: 'visibilityTimeout',
        label: 'Visibility Timeout (seconds)',
        type: 'number',
        default: 30,
      },
      {
        name: 'messageRetention',
        label: 'Message Retention (seconds)',
        type: 'number',
        default: 345600,
        description: '4 days default, max 14 days',
      },
      {
        name: 'maxMessageSize',
        label: 'Max Message Size (bytes)',
        type: 'number',
        default: 262144,
        description: 'Max 256 KB',
      },
      {
        name: 'delaySeconds',
        label: 'Delivery Delay (seconds)',
        type: 'number',
        default: 0,
      },
      {
        name: 'receiveWaitTime',
        label: 'Receive Wait Time (seconds)',
        type: 'number',
        default: 0,
        description: 'Long polling (0-20)',
      },
      {
        name: 'enableDlq',
        label: 'Enable Dead Letter Queue',
        type: 'boolean',
        default: false,
      },
      {
        name: 'maxReceiveCount',
        label: 'Max Receive Count',
        type: 'number',
        default: 3,
        description: 'Before sending to DLQ',
      },
      {
        name: 'enableEncryption',
        label: 'Enable Encryption',
        type: 'boolean',
        default: true,
      },
    ],
    terraformResource: 'aws_sqs_queue',
    pulumiClass: 'aws.sqs.Queue',
  },

  // VPC Environment Components
  {
    id: 'vpc-environment',
    name: 'VPC Environment',
    shortName: 'VPC',
    category: 'networking',
    description: 'Virtual network container with public and private subnets',
    color: '#8C4FFF',
    icon: 'network',
    allowedConnections: [],
    isContainer: true,
    properties: [
      {
        name: 'vpcName',
        label: 'VPC Name',
        type: 'text',
        default: 'my-vpc',
        description: 'Name for the VPC',
        required: true,
      },
      {
        name: 'cidrBlock',
        label: 'CIDR Block',
        type: 'text',
        default: '10.0.0.0/16',
        description: 'VPC CIDR block',
        required: true,
      },
      {
        name: 'enableDnsHostnames',
        label: 'DNS Hostnames',
        type: 'boolean',
        default: true,
        description: 'Enable DNS hostnames in the VPC',
      },
      {
        name: 'enableDnsSupport',
        label: 'DNS Support',
        type: 'boolean',
        default: true,
        description: 'Enable DNS support in the VPC',
      },
    ],
    terraformResource: 'aws_vpc',
    pulumiClass: 'aws.ec2.Vpc',
  },
  {
    id: 'public-subnet',
    name: 'Public Subnet',
    shortName: 'Pub',
    category: 'networking',
    description: 'Internet-accessible subnet with public IP assignment',
    color: '#22C55E',
    icon: 'globe',
    allowedConnections: [],
    isContainer: true,
    parentRequired: 'vpc-environment',
    properties: [
      {
        name: 'subnetName',
        label: 'Subnet Name',
        type: 'text',
        default: 'public-subnet',
        description: 'Name for the subnet',
        required: true,
      },
      {
        name: 'cidrBlock',
        label: 'CIDR Block',
        type: 'text',
        default: '10.0.1.0/24',
        description: 'Subnet CIDR block',
      },
      {
        name: 'availabilityZone',
        label: 'Availability Zone',
        type: 'select',
        default: 'us-east-1a',
        options: [
          { value: 'us-east-1a', label: 'us-east-1a' },
          { value: 'us-east-1b', label: 'us-east-1b' },
          { value: 'us-east-1c', label: 'us-east-1c' },
          { value: 'us-west-2a', label: 'us-west-2a' },
          { value: 'us-west-2b', label: 'us-west-2b' },
          { value: 'us-west-2c', label: 'us-west-2c' },
          { value: 'eu-west-1a', label: 'eu-west-1a' },
          { value: 'eu-west-1b', label: 'eu-west-1b' },
          { value: 'eu-west-1c', label: 'eu-west-1c' },
        ],
      },
    ],
    terraformResource: 'aws_subnet',
    pulumiClass: 'aws.ec2.Subnet',
  },
  {
    id: 'private-subnet',
    name: 'Private Subnet',
    shortName: 'Priv',
    category: 'networking',
    description: 'Internal-only subnet without public IP assignment',
    color: '#EF4444',
    icon: 'shield',
    allowedConnections: [],
    isContainer: true,
    parentRequired: 'vpc-environment',
    properties: [
      {
        name: 'subnetName',
        label: 'Subnet Name',
        type: 'text',
        default: 'private-subnet',
        description: 'Name for the subnet',
        required: true,
      },
      {
        name: 'cidrBlock',
        label: 'CIDR Block',
        type: 'text',
        default: '10.0.10.0/24',
        description: 'Subnet CIDR block',
      },
      {
        name: 'availabilityZone',
        label: 'Availability Zone',
        type: 'select',
        default: 'us-east-1a',
        options: [
          { value: 'us-east-1a', label: 'us-east-1a' },
          { value: 'us-east-1b', label: 'us-east-1b' },
          { value: 'us-east-1c', label: 'us-east-1c' },
          { value: 'us-west-2a', label: 'us-west-2a' },
          { value: 'us-west-2b', label: 'us-west-2b' },
          { value: 'us-west-2c', label: 'us-west-2c' },
          { value: 'eu-west-1a', label: 'eu-west-1a' },
          { value: 'eu-west-1b', label: 'eu-west-1b' },
          { value: 'eu-west-1c', label: 'eu-west-1c' },
        ],
      },
    ],
    terraformResource: 'aws_subnet',
    pulumiClass: 'aws.ec2.Subnet',
  },
  {
    id: 'alb',
    name: 'Application Load Balancer',
    shortName: 'ALB',
    category: 'networking',
    description: 'Layer 7 load balancer for HTTP/HTTPS traffic',
    color: '#8C4FFF',
    icon: 'git-branch',
    allowedConnections: ['ecs', 'ec2', 'lambda'],
    subnetPlacement: {
      allowedInPublic: true,
      allowedInPrivate: false,
      requiresSubnet: true,
    },
    properties: [
      {
        name: 'albName',
        label: 'ALB Name',
        type: 'text',
        default: 'my-alb',
        description: 'Name for the load balancer',
        required: true,
      },
      {
        name: 'internal',
        label: 'Internal',
        type: 'boolean',
        default: false,
        description: 'If true, ALB is internal (not internet-facing)',
      },
      {
        name: 'idleTimeout',
        label: 'Idle Timeout (seconds)',
        type: 'number',
        default: 60,
        description: 'Connection idle timeout (1-4000)',
      },
      {
        name: 'enableHttp2',
        label: 'Enable HTTP/2',
        type: 'boolean',
        default: true,
      },
      {
        name: 'enableDeletionProtection',
        label: 'Deletion Protection',
        type: 'boolean',
        default: false,
        description: 'Prevent accidental deletion',
      },
      {
        name: 'listenerPort',
        label: 'Listener Port',
        type: 'number',
        default: 80,
        description: 'Port for the default listener',
      },
      {
        name: 'targetPort',
        label: 'Target Port',
        type: 'number',
        default: 80,
        description: 'Port on targets to route traffic to',
      },
      {
        name: 'healthCheckPath',
        label: 'Health Check Path',
        type: 'text',
        default: '/',
        description: 'Path for health checks',
      },
    ],
    terraformResource: 'aws_lb',
    pulumiClass: 'aws.lb.LoadBalancer',
  },
  {
    id: 'nlb',
    name: 'Network Load Balancer',
    shortName: 'NLB',
    category: 'networking',
    description: 'Layer 4 load balancer for TCP/UDP traffic',
    color: '#8C4FFF',
    icon: 'git-branch',
    allowedConnections: ['ecs', 'ec2'],
    subnetPlacement: {
      allowedInPublic: true,
      allowedInPrivate: true,
      requiresSubnet: true,
    },
    properties: [
      {
        name: 'nlbName',
        label: 'NLB Name',
        type: 'text',
        default: 'my-nlb',
        description: 'Name for the load balancer',
        required: true,
      },
      {
        name: 'internal',
        label: 'Internal',
        type: 'boolean',
        default: false,
        description: 'If true, NLB is internal',
      },
      {
        name: 'enableCrossZone',
        label: 'Cross-Zone Load Balancing',
        type: 'boolean',
        default: true,
        description: 'Distribute traffic across all AZs',
      },
      {
        name: 'listenerPort',
        label: 'Listener Port',
        type: 'number',
        default: 80,
        description: 'Port for the default listener',
      },
      {
        name: 'targetPort',
        label: 'Target Port',
        type: 'number',
        default: 80,
        description: 'Port on targets to route traffic to',
      },
    ],
    terraformResource: 'aws_lb',
    pulumiClass: 'aws.lb.LoadBalancer',
  },
  {
    id: 'nat-gateway',
    name: 'NAT Gateway',
    shortName: 'NAT',
    category: 'networking',
    description: 'Network address translation for private subnet internet access',
    color: '#8C4FFF',
    icon: 'arrow-right-left',
    allowedConnections: [],
    subnetPlacement: {
      allowedInPublic: true,
      allowedInPrivate: false,
      requiresSubnet: true,
    },
    properties: [
      {
        name: 'natName',
        label: 'NAT Name',
        type: 'text',
        default: 'my-nat',
        description: 'Name for the NAT Gateway',
        required: true,
      },
      {
        name: 'connectivityType',
        label: 'Connectivity Type',
        type: 'select',
        default: 'public',
        options: [
          { value: 'public', label: 'Public (requires EIP)' },
          { value: 'private', label: 'Private' },
        ],
      },
    ],
    terraformResource: 'aws_nat_gateway',
    pulumiClass: 'aws.ec2.NatGateway',
  },
];

export function getServiceById(id: string): AWSService | undefined {
  return awsServices.find((s) => s.id === id);
}

export function getServicesByCategory(category: string): AWSService[] {
  return awsServices.filter((s) => s.category === category);
}

export function canConnect(sourceId: string, targetId: string): boolean {
  const source = getServiceById(sourceId);
  const target = getServiceById(targetId);
  if (!source || !target) return false;

  // Allow connection if either service lists the other in allowedConnections
  // This enables bidirectional relationships (e.g., CloudFront -> S3 or S3 -> CloudFront)
  return (
    source.allowedConnections.includes(targetId) ||
    target.allowedConnections.includes(sourceId)
  );
}
